In [1]:
import pandas as pd

In [3]:
df1= pd.read_parquet("/Users/ritikahiremath/Downloads/Data/OK_Measurements/2024.02.14_22.00.10_Grinding/raw/Sampling100KHz_Irms_Grinding-Grinding spindle current L1-Grinding spindle current L2-Grinding spindle current L3-0.parquet")

In [4]:
df1

,Irms_Grinding_rate100000_clipping0_batch0,Grinding spindle current L1_rate100000_clipping0_batch0,Grinding spindle current L2_rate100000_clipping0_batch0,Grinding spindle current L3_rate100000_clipping0_batch0
0,0.103928,-0.115736,0.027999,0.134996
1,0.109450,-0.129770,0.045377,0.130532
2,0.109388,-0.109039,0.028947,0.152216
3,0.111707,-0.116374,0.028631,0.151897
4,0.113854,-0.125943,0.030211,0.148708
...,...,...,...,...
2280573,0.027839,0.026832,0.024524,0.031680
2280574,0.023175,-0.007933,0.037794,0.010953
2280575,0.019097,-0.010485,0.028315,0.013504
2280576,0.023368,-0.027389,0.029579,0.003619
2280577,0.015131,-0.011123,0.014729,0.018606

In [5]:
df2= pd.read_parquet("/Users/ritikahiremath/Downloads/Data/OK_Measurements/2024.02.14_22.00.10_Grinding/raw/Sampling2000KHz_AEKi-0.parquet")

In [6]:
df2

          AEKi_rate2000000_clipping0_batch0
0                                 -0.000679
1                                  0.003445
2                                 -0.000679
3                                 -0.002053
4                                 -0.000679
...                                     ...
45613115                          -0.000679
45613116                           0.002070
45613117                           0.007568
45613118                           0.000696
45613119                          -0.010300

[45613120 rows x 1 columns]